# Generated by Django 5.1.4 on 2025-02-12 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flagapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='mail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='contact',
        ),
        migrations.AddField(
            model_name='registration',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=600.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='course',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
